### ISSUE TITLE
Could Rqtl2 handle genotypes of CP population coded in JoinMap format?

### ISSUE THREAD

**Issue by JiaoBingke** [rqtl/qtl2data#9]
Dear Professor @kbroman ,

I builded a genetic map of a CP population using JoinMap.  Now I want to put the genotypes encoded in JoinMap format into Rqlt2 format.  According to the manual of JoinMap, the CP population is a population from a cross bewteen two heterogeneously heterozygous and homozygous diploid parents, linkage phases originally possibly unknown. In the genotype file corresponding to the consensus map, the marker types are ll, lm, nn, np, hk, hh, kk, just like below.

`REGS638-2377348-7    <lmxll> {0-}  ; S/n:1, Nr:1412, 0.000 cM
   ll lm lm ll ll  ll ll ll lm lm  ll ll lm lm ll  ll lm lm lm ll  lm ll ll lm ll
   lm lm ll lm ll  lm lm ll lm lm  lm lm ll ll lm  lm lm lm lm ll  ll lm ll ll ll
   lm ll lm lm ll  ll lm ll ll ll  ll ll ll ll ll  ll ll ll ll lm  lm lm ll ll lm
   ll lm ll lm lm  -- ll ll lm ll  ll ll ll lm lm  ll ll ll ll ll  ll ll ll ll ll
   ll ll -- lm ll  lm ll lm ll lm  lm lm ll ll ll  ll ll ll ll ll  lm lm -- ll ll
   ll ll ll ll ll  -- lm ll lm lm  lm lm ll ll lm  lm lm
REGS638-76368-14     <hkxhk> {01}  ; S/n:2, Nr:1401, 0.645 cM
   hh hk hk hh hk  hk hk hh hk kk  hh hk hk kk hh  hk kk kk hk hh  hk hk hh kk hk
   kk kk hh kk hh  hh kk hk hk kk  kk hh hk hh kk  kk hk hk kk hh  hh kk hh hk hk
   hh hh hk kk hh  hk kk hk hk hh  -- hk hk hh hh  hh kk hk hh hk  kk hk hh hk hh
   -- hh hh hk kk  hk hk hh -- hk  hh hh -- kk hk  -- hk hk hk hh  hk -- hk hh hk
   hh kk kk hk hh  kk hh hk hh kk  hk hk hh hh hh  hk hk kk kk hh  kk hk kk hh kk
   -- hh kk hh hk  kk kk hh kk hk  kk kk hh hk kk  kk hk
`
 **I don't know whether Rqtl2 can accept genotypes of CP population. If so, how can I encode genotypes in Rqtl2 format?** After I read the cross types in manual of Rqtl2, I didn't find an appropriate corss type among bc, f2,etc.

Thanks a lot. I wish to your reply.
Sincerely yours
Jiao

**Comment by kbroman** [comment]
No, [R/qtl2](https://github.com/rqtl/qtl2) can’t currently handle such outbred crosses.

**Comment by JiaoBingke** [comment]
Thank you for your reply.
